# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateUser.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreateUser(object):
    def setupUi(self, CreateUser):
        CreateUser.setObjectName("CreateUser")
        CreateUser.setEnabled(True)
        CreateUser.resize(413, 578)
        CreateUser.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cct/paints.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CreateUser.setWindowIcon(icon)
        CreateUser.setLayoutDirection(QtCore.Qt.LeftToRight)
        CreateUser.setStyleSheet("background-color: rgb(51, 102, 153);")
        self.centralwidget = QtWidgets.QWidget(CreateUser)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 70, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 60, 181, 91))
        self.label_2.setStyleSheet("border-image: url(:/cct/paints.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 120, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.buttonCreate = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCreate.setGeometry(QtCore.QRect(110, 440, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buttonCreate.setFont(font)
        self.buttonCreate.setStyleSheet("color: rgb(245, 245, 245);\n"
"background-color: rgb(2, 233, 10);")
        self.buttonCreate.setObjectName("buttonCreate")
        self.textEditPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.textEditPassword.setEnabled(True)
        self.textEditPassword.setGeometry(QtCore.QRect(80, 360, 251, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.textEditPassword.setFont(font)
        self.textEditPassword.setStyleSheet("background-color: rgb(206, 201, 206);")
        self.textEditPassword.setInputMask("")
        self.textEditPassword.setText("")
        self.textEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.textEditPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.textEditPassword.setObjectName("textEditPassword")
        self.textEditName = QtWidgets.QLineEdit(self.centralwidget)
        self.textEditName.setEnabled(True)
        self.textEditName.setGeometry(QtCore.QRect(80, 200, 251, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.textEditName.setFont(font)
        self.textEditName.setStyleSheet("background-color: rgb(206, 201, 206);")
        self.textEditName.setInputMask("")
        self.textEditName.setText("")
        self.textEditName.setAlignment(QtCore.Qt.AlignCenter)
        self.textEditName.setObjectName("textEditName")
        self.textEditUserName = QtWidgets.QLineEdit(self.centralwidget)
        self.textEditUserName.setEnabled(True)
        self.textEditUserName.setGeometry(QtCore.QRect(80, 280, 251, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.textEditUserName.setFont(font)
        self.textEditUserName.setStyleSheet("background-color: rgb(206, 201, 206);")
        self.textEditUserName.setInputMask("")
        self.textEditUserName.setText("")
        self.textEditUserName.setAlignment(QtCore.Qt.AlignCenter)
        self.textEditUserName.setObjectName("textEditUserName")
        self.labelSuccessfull = QtWidgets.QLabel(self.centralwidget)
        self.labelSuccessfull.setGeometry(QtCore.QRect(90, 500, 221, 31))
        self.labelSuccessfull.setObjectName("labelSuccessfull")
        self.buttonReturnMenu = QtWidgets.QPushButton(self.centralwidget)
        self.buttonReturnMenu.setGeometry(QtCore.QRect(310, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buttonReturnMenu.setFont(font)
        self.buttonReturnMenu.setStyleSheet("color: rgb(245, 245, 245);\n"
"background-color: rgb(22, 155, 175);")
        self.buttonReturnMenu.setObjectName("buttonReturnMenu")
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.buttonCreate.raise_()
        self.textEditPassword.raise_()
        self.textEditName.raise_()
        self.textEditUserName.raise_()
        self.labelSuccessfull.raise_()
        self.buttonReturnMenu.raise_()
        CreateUser.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CreateUser)
        self.statusbar.setObjectName("statusbar")
        CreateUser.setStatusBar(self.statusbar)

        self.retranslateUi(CreateUser)
        QtCore.QMetaObject.connectSlotsByName(CreateUser)

    def retranslateUi(self, CreateUser):
        _translate = QtCore.QCoreApplication.translate
        CreateUser.setWindowTitle(_translate("CreateUser", "DrawingApp"))
        self.label.setText(_translate("CreateUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-style:italic; color:#ececec;\">CREATE</span></p></body></html>"))
        self.label_3.setText(_translate("CreateUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-style:italic; color:#ececec;\">USER</span></p></body></html>"))
        self.buttonCreate.setText(_translate("CreateUser", "CREATE"))
        self.textEditPassword.setPlaceholderText(_translate("CreateUser", "PASSWORD"))
        self.textEditName.setPlaceholderText(_translate("CreateUser", "NAME"))
        self.textEditUserName.setPlaceholderText(_translate("CreateUser", "USER NAME"))
        self.labelSuccessfull.setText(_translate("CreateUser", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.buttonReturnMenu.setText(_translate("CreateUser", "RETURN"))

import portada_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateUser = QtWidgets.QMainWindow()
    ui = Ui_CreateUser()
    ui.setupUi(CreateUser)
    CreateUser.show()
    sys.exit(app.exec_())

