# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateUser.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UpdateUser(object):
    def setupUi(self, UpdateUser):
        UpdateUser.setObjectName("UpdateUser")
        UpdateUser.setEnabled(True)
        UpdateUser.resize(413, 495)
        UpdateUser.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cct/paints.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UpdateUser.setWindowIcon(icon)
        UpdateUser.setLayoutDirection(QtCore.Qt.LeftToRight)
        UpdateUser.setStyleSheet("background-color: rgb(51, 102, 153);")
        self.centralwidget = QtWidgets.QWidget(UpdateUser)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 70, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 60, 181, 91))
        self.label_2.setStyleSheet("border-image: url(:/cct/paints.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 120, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.buttonUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.buttonUpdate.setGeometry(QtCore.QRect(120, 360, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buttonUpdate.setFont(font)
        self.buttonUpdate.setStyleSheet("color: rgb(245, 245, 245);\n"
"background-color: rgb(233, 236, 22);")
        self.buttonUpdate.setObjectName("buttonUpdate")
        self.textEditPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.textEditPassword.setEnabled(True)
        self.textEditPassword.setGeometry(QtCore.QRect(90, 280, 251, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.textEditPassword.setFont(font)
        self.textEditPassword.setStyleSheet("background-color: rgb(206, 201, 206);")
        self.textEditPassword.setInputMask("")
        self.textEditPassword.setText("")
        self.textEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.textEditPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.textEditPassword.setObjectName("textEditPassword")
        self.textEditName = QtWidgets.QLineEdit(self.centralwidget)
        self.textEditName.setEnabled(True)
        self.textEditName.setGeometry(QtCore.QRect(90, 200, 251, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.textEditName.setFont(font)
        self.textEditName.setStyleSheet("background-color: rgb(206, 201, 206);")
        self.textEditName.setInputMask("")
        self.textEditName.setText("")
        self.textEditName.setAlignment(QtCore.Qt.AlignCenter)
        self.textEditName.setObjectName("textEditName")
        self.labelSuccessful = QtWidgets.QLabel(self.centralwidget)
        self.labelSuccessful.setGeometry(QtCore.QRect(100, 420, 221, 31))
        self.labelSuccessful.setObjectName("labelSuccessful")
        self.buttonReturn = QtWidgets.QPushButton(self.centralwidget)
        self.buttonReturn.setGeometry(QtCore.QRect(300, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buttonReturn.setFont(font)
        self.buttonReturn.setStyleSheet("color: rgb(245, 245, 245);\n"
"background-color: rgb(23, 170, 199);")
        self.buttonReturn.setObjectName("buttonReturn")
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.buttonUpdate.raise_()
        self.textEditPassword.raise_()
        self.textEditName.raise_()
        self.labelSuccessful.raise_()
        self.buttonReturn.raise_()
        UpdateUser.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(UpdateUser)
        self.statusbar.setObjectName("statusbar")
        UpdateUser.setStatusBar(self.statusbar)

        self.retranslateUi(UpdateUser)
        QtCore.QMetaObject.connectSlotsByName(UpdateUser)

    def retranslateUi(self, UpdateUser):
        _translate = QtCore.QCoreApplication.translate
        UpdateUser.setWindowTitle(_translate("UpdateUser", "DrawingApp"))
        self.label.setText(_translate("UpdateUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-style:italic; color:#ececec;\">UPDATE</span></p></body></html>"))
        self.label_3.setText(_translate("UpdateUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-style:italic; color:#ececec;\">USER</span></p></body></html>"))
        self.buttonUpdate.setText(_translate("UpdateUser", "UPDATE"))
        self.textEditPassword.setPlaceholderText(_translate("UpdateUser", "PASSWORD"))
        self.textEditName.setPlaceholderText(_translate("UpdateUser", "NAME"))
        self.labelSuccessful.setText(_translate("UpdateUser", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.buttonReturn.setText(_translate("UpdateUser", "RETURN"))

import portada_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UpdateUser = QtWidgets.QMainWindow()
    ui = Ui_UpdateUser()
    ui.setupUi(UpdateUser)
    UpdateUser.show()
    sys.exit(app.exec_())

